name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
        
    steps:
    - uses: actions/checkout@v4
    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assemble with Gradle
      run: ./gradlew assemble

    - name: Archive produced firmware
      uses: actions/upload-artifact@v5
      with:
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/
